import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
from biollm import SparkBrainBlock, HippocampalMemory

class LMHead(nn.Module):
    def __init__(self, d_model: int, vocab_size: int):
        super().__init__()
        self.linear = nn.Linear(d_model, vocab_size)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(x)

def run_inference(
    prompt: str, 
    max_tokens: int = 100, 
    temperature: float = 0.7, 
    checkpoint_path: str = "biollm_checkpoint.pt",
    d_model: int = 256,
    expert_dim: int = 1024,
    num_experts: int = 8,
    num_layers: int = 3,
    compile_model: bool = False
):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"==================================================")
    print(f"BioLLM Local Inference on: {device}")
    print(f"Loading checkpoint from: {checkpoint_path}")
    print(f"==================================================")
    
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint file {checkpoint_path} not found. Please train the model first.")
        
    vocab_size = 256
    
    # Load checkpoint first to auto-detect architecture parameters
    checkpoint = torch.load(checkpoint_path, map_location=device)
    
    # Auto-detect hyperparameters from tensor shapes
    d_model = checkpoint["embedding"]["weight"].shape[1]
    num_layers = len(checkpoint["layers"])
    num_experts = checkpoint["layers"][0]["raw_inhibitory_weights"].shape[0]
    # Under nn.Sequential in experts: experts[0][0] is NVFP4Linear(d_model, expert_dim)
    expert_dim = checkpoint["layers"][0]["experts.0.0.weight"].shape[0]
    
    print(f"Auto-detected architecture configurations:")
    print(f" - d_model: {d_model}")
    print(f" - expert_dim: {expert_dim}")
    print(f" - num_experts: {num_experts}")
    print(f" - num_layers: {num_layers}")
    
    # 1. Initialize Architecture
    embedding = nn.Embedding(vocab_size, d_model).to(device).bfloat16()
    lm_head = LMHead(d_model, vocab_size).to(device).bfloat16()
    layers = [
        SparkBrainBlock(d_model=d_model, num_experts=num_experts, expert_dim=expert_dim).to(device).bfloat16()
        for _ in range(num_layers)
    ]
    memory = HippocampalMemory(d_model=d_model, memory_size=512, decay_rate=0.98).to(device).bfloat16()
    
    # 2. Load Weights from Checkpoint
    embedding.load_state_dict(checkpoint["embedding"])
    for idx, layer in enumerate(layers):
        layer.load_state_dict(checkpoint["layers"][idx])
    lm_head.load_state_dict(checkpoint["lm_head"])
    
    memory.keys.copy_(checkpoint["memory_keys"])
    memory.values.copy_(checkpoint["memory_values"])
    memory.strengths.copy_(checkpoint["memory_strengths"])
    print("Model loaded successfully.")
    
    if compile_model:
        print("Compiling model blocks for optimized inference (this may take a minute)...")
        layers = [torch.compile(layer) for layer in layers]
        lm_head = torch.compile(lm_head)
    
    # Initialize Transformer Engine (TE) Native FP4 Context
    from biollm.layers.nvfp4 import HAS_TE
    if HAS_TE:
        import transformer_engine.pytorch as te
        from transformer_engine.common.recipe import Format, NVFP4BlockScaling
        print("Transformer Engine detected. Enabling native Blackwell NVFP4 (E2M1) inference...")
        recipe = NVFP4BlockScaling()
        def native_fp4_autocast():
            return te.autocast(enabled=True, recipe=recipe)
    else:
        import contextlib
        def native_fp4_autocast():
            return contextlib.nullcontext()
    
    
    # 3. Process Input Prompt
    # Convert string prompt to byte token IDs
    prompt_bytes = list(prompt.encode("utf-8", errors="ignore"))
    input_ids = torch.tensor([prompt_bytes], dtype=torch.long, device=device) # Shape: [1, seq_len]
    
    print(f"\nPrompt: '{prompt}'")
    print("Generated Text: ", end="", flush=True)
    
    # Track generated bytes
    generated_bytes = list(prompt_bytes)
    
    # 4. Prefill Phase (process initial prompt context in one batch pass)
    with torch.no_grad():
        with native_fp4_autocast():
            prompt_embeddings = embedding(input_ids) # [1, prompt_len, d_model]
            retrieved_context = memory.read(prompt_embeddings, temperature=0.5)
            hidden = prompt_embeddings + retrieved_context
            
            for layer in layers:
                hidden = layer(hidden)
                
            # Write prompt states to episodic memory
            flat_keys = prompt_embeddings[0].view(-1, d_model)
            flat_vals = hidden[0].view(-1, d_model)
            memory.write(flat_keys, flat_vals)
            
            # Get initial logits for the last token in prompt to seed loop
            norm_hidden = (hidden - hidden.mean(dim=-1, keepdim=True)) / (hidden.std(dim=-1, keepdim=True) + 1e-5)
            logits = lm_head(norm_hidden[:, -1, :])
            
            if temperature > 0:
                probs = F.softmax(logits / temperature, dim=-1)
                next_token_id = torch.multinomial(probs, num_samples=1).item()
            else:
                next_token_id = torch.argmax(logits, dim=-1).item()
                
            generated_bytes.append(next_token_id)
            try:
                char = bytes([next_token_id]).decode("utf-8")
                print(char, end="", flush=True)
            except UnicodeDecodeError:
                pass

    # 5. O(1) Autoregressive Generation Loop (process only the newly generated token)
    for _ in range(max_tokens - 1):
        with torch.no_grad():
            with native_fp4_autocast():
                token_input = torch.tensor([[next_token_id]], dtype=torch.long, device=device)
                token_embedding = embedding(token_input) # [1, 1, d_model]
                
                # Read episodic memory context for single new token
                retrieved_context = memory.read(token_embedding, temperature=0.5)
                hidden = token_embedding + retrieved_context
                
                for layer in layers:
                    hidden = layer(hidden)
                    
                norm_hidden = (hidden - hidden.mean(dim=-1, keepdim=True)) / (hidden.std(dim=-1, keepdim=True) + 1e-5)
                logits = lm_head(norm_hidden[:, -1, :])
                
                if temperature > 0:
                    probs = F.softmax(logits / temperature, dim=-1)
                    next_token_id = torch.multinomial(probs, num_samples=1).item()
                else:
                    next_token_id = torch.argmax(logits, dim=-1).item()
                    
                generated_bytes.append(next_token_id)
                try:
                    char = bytes([next_token_id]).decode("utf-8")
                    print(char, end="", flush=True)
                except UnicodeDecodeError:
                    pass
                    
                # Write only the newly generated token state to episodic memory
                memory.write(token_embedding[0].view(-1, d_model), hidden[0].view(-1, d_model))
                
    # Final full decode to handle any trailing characters
    final_output = bytes(generated_bytes).decode("utf-8", errors="replace")
    print(f"\n\nFull output sequence:\n{final_output}")
    print(f"==================================================")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BioLLM Local Inference Utility")
    parser.add_argument(
        "--prompt", 
        type=str, 
        default="The brain is", 
        help="Input text prompt for generation"
    )
    parser.add_argument(
        "--tokens", 
        type=int, 
        default=50, 
        help="Number of tokens to generate"
    )
    parser.add_argument(
        "--temp", 
        type=float, 
        default=0.7, 
        help="Sampling temperature (0.0 for greedy decoding)"
    )
    parser.add_argument(
        "--checkpoint", 
        type=str, 
        default="biollm_checkpoint.pt", 
        help="Path to trained checkpoint file"
    )
    parser.add_argument(
        "--d_model", 
        type=int, 
        default=256, 
        help="Hidden dimension size of the model"
    )
    parser.add_argument(
        "--expert_dim", 
        type=int, 
        default=1024, 
        help="Expert bottleneck dimension"
    )
    parser.add_argument(
        "--experts", 
        type=int, 
        default=8, 
        help="Number of experts per layer"
    )
    parser.add_argument(
        "--layers", 
        type=int, 
        default=3, 
        help="Number of layers in the model"
    )
    parser.add_argument(
        "--compile",
        action="store_true",
        help="Compile model blocks using torch.compile for optimized execution"
    )
    args = parser.parse_args()
    
    run_inference(
        prompt=args.prompt,
        max_tokens=args.tokens,
        temperature=args.temp,
        checkpoint_path=args.checkpoint,
        d_model=args.d_model,
        expert_dim=args.expert_dim,
        num_experts=args.experts,
        num_layers=args.layers,
        compile_model=args.compile
    )
