import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
from biollm import SparkBrainBlock, HippocampalMemory

class LMHead(nn.Module):
    def __init__(self, d_model: int, vocab_size: int):
        super().__init__()
        self.linear = nn.Linear(d_model, vocab_size)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(x)

def run_inference(
    prompt: str, 
    max_tokens: int = 100, 
    temperature: float = 0.7, 
    checkpoint_path: str = "biollm_checkpoint.pt",
    d_model: int = 256,
    expert_dim: int = 1024,
    num_experts: int = 8,
    num_layers: int = 3
):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"==================================================")
    print(f"BioLLM Local Inference on: {device}")
    print(f"Loading checkpoint from: {checkpoint_path}")
    print(f"==================================================")
    
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint file {checkpoint_path} not found. Please train the model first.")
        
    vocab_size = 256
    
    # Load checkpoint first to auto-detect architecture parameters
    checkpoint = torch.load(checkpoint_path, map_location=device)
    
    # Auto-detect hyperparameters from tensor shapes
    d_model = checkpoint["embedding"]["weight"].shape[1]
    num_layers = len(checkpoint["layers"])
    num_experts = checkpoint["layers"][0]["excitatory_router.weight"].shape[0]
    # Under nn.Sequential in experts: experts[0][0] is NVFP4Linear(d_model, expert_dim)
    expert_dim = checkpoint["layers"][0]["experts.0.0.weight"].shape[0]
    
    print(f"Auto-detected architecture configurations:")
    print(f" - d_model: {d_model}")
    print(f" - expert_dim: {expert_dim}")
    print(f" - num_experts: {num_experts}")
    print(f" - num_layers: {num_layers}")
    
    # 1. Initialize Architecture
    embedding = nn.Embedding(vocab_size, d_model).to(device)
    lm_head = LMHead(d_model, vocab_size).to(device)
    layers = [
        SparkBrainBlock(d_model=d_model, num_experts=num_experts, expert_dim=expert_dim).to(device)
        for _ in range(num_layers)
    ]
    memory = HippocampalMemory(d_model=d_model, memory_size=512, decay_rate=0.98).to(device)
    
    # 2. Load Weights from Checkpoint
    embedding.load_state_dict(checkpoint["embedding"])
    for idx, layer in enumerate(layers):
        layer.load_state_dict(checkpoint["layers"][idx])
    lm_head.load_state_dict(checkpoint["lm_head"])
    
    # Restore memory bank states
    memory.keys.copy_(checkpoint["memory_keys"])
    memory.values.copy_(checkpoint["memory_values"])
    memory.strengths.copy_(checkpoint["memory_strengths"])
    print("Model loaded successfully.")
    
    # 3. Process Input Prompt
    # Convert string prompt to byte token IDs
    prompt_bytes = list(prompt.encode("utf-8", errors="ignore"))
    input_ids = torch.tensor([prompt_bytes], dtype=torch.long, device=device) # Shape: [1, seq_len]
    
    print(f"\nPrompt: '{prompt}'")
    print("Generated Text: ", end="", flush=True)
    
    # Track generated bytes
    generated_bytes = list(prompt_bytes)
    
    # 4. Autoregressive Generation Loop
    for _ in range(max_tokens):
        # We only pass the current input ids through the network
        with torch.no_grad():
            # Get embeddings for current sequence
            seq_embeddings = embedding(input_ids) # [1, current_len, d_model]
            
            # Read relevant context from episodic memory
            retrieved_context = memory.read(seq_embeddings, temperature=0.5)
            
            # Combine current representations and retrieved episodic context
            hidden = seq_embeddings + retrieved_context
            
            # Forward pass through Spark layers
            for layer in layers:
                hidden = layer(hidden)
                
            # Normalize representation before passing to LM Head to avoid magnitude explosion issues
            norm_hidden = (hidden - hidden.mean(dim=-1, keepdim=True)) / (hidden.std(dim=-1, keepdim=True) + 1e-5)
            
            # Get logits for the LAST token in the sequence
            logits = lm_head(norm_hidden[:, -1, :]) # [1, vocab_size]
            
            # Apply temperature scaling
            if temperature > 0:
                probs = F.softmax(logits / temperature, dim=-1)
                next_token_id = torch.multinomial(probs, num_samples=1).item()
            else:
                next_token_id = torch.argmax(logits, dim=-1).item()
                
            # Append generated byte token to list
            generated_bytes.append(next_token_id)
            
            # Print character as we decode it
            # Decode the newly generated byte to character if possible
            try:
                char = bytes([next_token_id]).decode("utf-8")
                print(char, end="", flush=True)
            except UnicodeDecodeError:
                # Handle partial multi-byte UTF-8 sequences by just skipping direct output
                # (it will be fully decoded at the end)
                pass
                
            # Write new state representation into hippocampal episodic memory
            flat_keys = seq_embeddings[0].view(-1, d_model)
            flat_vals = hidden[0].view(-1, d_model)
            memory.write(flat_keys[-1:], flat_vals[-1:])
            
            # Update input_ids for the next step (add new token to the sequence window)
            # Keeping context length bound if it gets too large
            new_token_tensor = torch.tensor([[next_token_id]], dtype=torch.long, device=device)
            input_ids = torch.cat([input_ids, new_token_tensor], dim=-1)
            if input_ids.size(-1) > 128:  # context window constraint
                input_ids = input_ids[:, -128:]
                
    # Final full decode to handle any trailing characters
    final_output = bytes(generated_bytes).decode("utf-8", errors="replace")
    print(f"\n\nFull output sequence:\n{final_output}")
    print(f"==================================================")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BioLLM Local Inference Utility")
    parser.add_argument(
        "--prompt", 
        type=str, 
        default="The brain is", 
        help="Input text prompt for generation"
    )
    parser.add_argument(
        "--tokens", 
        type=int, 
        default=50, 
        help="Number of tokens to generate"
    )
    parser.add_argument(
        "--temp", 
        type=float, 
        default=0.7, 
        help="Sampling temperature (0.0 for greedy decoding)"
    )
    parser.add_argument(
        "--checkpoint", 
        type=str, 
        default="biollm_checkpoint.pt", 
        help="Path to trained checkpoint file"
    )
    parser.add_argument(
        "--d_model", 
        type=int, 
        default=256, 
        help="Hidden dimension size of the model"
    )
    parser.add_argument(
        "--expert_dim", 
        type=int, 
        default=1024, 
        help="Expert bottleneck dimension"
    )
    parser.add_argument(
        "--experts", 
        type=int, 
        default=8, 
        help="Number of experts per layer"
    )
    parser.add_argument(
        "--layers", 
        type=int, 
        default=3, 
        help="Number of layers in the model"
    )
    args = parser.parse_args()
    
    run_inference(
        prompt=args.prompt,
        max_tokens=args.tokens,
        temperature=args.temp,
        checkpoint_path=args.checkpoint,
        d_model=args.d_model,
        expert_dim=args.expert_dim,
        num_experts=args.experts,
        num_layers=args.layers
    )
